In [1]:
import pandas as pd

In [6]:
results = pd.read_csv('results_overall_simple.csv')

results

              Model       MAE       RMSE    MAPE(%)        R2  Accuracy(%)
0  NaivePersistence  7.256501  16.943109  13.984277  0.988962    86.015723
1          CNN_LSTM  9.573442  17.718961  28.291024  0.987928    71.708976
2               GRU  9.069550  18.741582  15.588940  0.986495    84.411060
3             DENSE  9.830869  19.266972  20.048764  0.985727    79.951236

In [7]:
results_per_feature = pd.read_csv('results_per_feature_simple.csv')

results_per_feature

,Model,Feature,MAE,RMSE,MAPE(%),R2,Accuracy(%)
0,NaivePersistence,PM2.5,10.146816,15.719890,22.497837,0.681885,77.502163
1,NaivePersistence,PM10,18.226551,30.007501,26.073426,0.558762,73.926574
2,NaivePersistence,CO,0.293064,0.567741,7.277447,0.687984,92.722553
3,NaivePersistence,CO2,0.359572,0.623180,0.088400,0.839044,99.911600
4,GRU,PM2.5,12.785861,18.023707,24.462491,0.581810,75.537509
5,GRU,PM10,21.738219,32.822958,26.415104,0.472079,73.584896
6,GRU,CO,0.460469,0.677421,11.160316,0.555785,88.839684
7,GRU,CO2,1.293652,1.525835,0.317848,0.035073,99.682152
8,CNN_LSTM,PM2.5,14.279663,18.031936,41.856028,0.581428,58.143972
9,CNN_LSTM,PM10,21.883436,30.446753,42.339733,0.545750,57.660267
10,CNN_LSTM,CO,1.138405,1.365340,28.724803,-0.804504,71.275197
11,CNN_LSTM,CO2,0.992264,1.351576,0.243533,0.242888,99.756467
12,DENSE,PM2.5,15.206986,20.357137,34.432669,0.466519,65.567331
13,DENSE,PM10,22.177645,32.666660,30.980047,0.477095,69.019953
14,DENSE,CO,0.574309,0.817967,14.447071,0.352340,85.552929
15,DENSE,CO2,1.364538,1.634618,0.335269,-0.107419,99.664731